name: hyper_authenticator
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  supabase_flutter: ^2.8.4
  http: ^1.3.0
  go_router: ^14.8.1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  intl: ^0.20.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_dotenv: ^5.2.1
  bloc: ^9.0.0
  fpdart: ^1.1.1
  supabase_auth_ui: ^0.5.4
  flutter_native_splash: ^2.4.0

  # Core Authenticator Features
  flutter_secure_storage: ^9.0.0 # Secure storage for secret keys
  otp: ^3.1.0                   # TOTP generation
  mobile_scanner: ^5.1.0        # QR code scanning
  local_auth: ^2.2.0            # Biometric/PIN lock
  uuid: ^4.3.3                  # For generating unique IDs
  shared_preferences: ^2.2.3    # For storing settings like biometric toggle
  local_auth_windows: ^1.0.11
  cryptography: ^2.7.0 # Added for encryption features (even if sync is simple now) - Updated version
  provider: ^6.1.2             # For state management (e.g., ThemeProvider)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Add this line

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  rename: ^3.0.2 # Add this line (check pub.dev for latest version if needed)



flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/hyper-logo-green-non-bg-alt.png
  #  branding: assets/images/email-service.png
  color_dark: "#000000"
  image_dark: assets/logos/hyper-logo-green-non-bg-alt.png
  #  branding_dark: assets/images/email-service.png

  android_12:
    image: assets/logos/android12splash-hyper-alt.png
    # icon_background_color: "#ffffff" # Removed, usually not needed with image
    image_dark: assets/logos/android12splash-hyper-alt.png
    # icon_background_color_dark: "#000000" # Removed, usually not needed with image_dark

  web: false
  fullscreen: false # Changed to false for better compatibility with Android 12+ standard behavior


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/logos/
    - assets/logos/authenticators/
    - assets/data/authenticator_logo_map.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/averta.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/hyper-logo-green-black.png" # Make sure this path is correct
  min_sdk_android: 21 # Optional: you can specify a minimum SDK level
  windows:
    generate: true
    image_path: "assets/logos/hyper-logo-green-black.png"
    icon_size: 256 # Or 48, depending on your needs
  macos:
    generate: true
    image_path: "assets/logos/hyper-logo-green-black.png"
