services:
  reset-password-web:
    networks:
      - proxy-network
      - supabase-network

networks:
  proxy-network:
    external: true
    name: proxy-network
  supabase-network:
    external: true
    name: supabase_default
